paths:
  sbml: input/tomato_cobra_boundaries.xml
  leaf_cons: input/constraints_tomato_day.txt
  stem_cons: input/constraints_tomato_day.txt
  root_cons: input/constraints_tomato_day.txt
# relative paths start in the repo directory.
# use absolute paths for files located elsewhere.

biomass_rate:
  leaf: 0.21
  stem: 0.26
  root: 0.17

dry_weight_ratios:
  leaf/root: 3.37
  stem/root: 1.52