paths:
  # relative paths start in the repo directory.
  # use absolute paths for files located elsewhere.
  sbml: input/tomato_cobra_boundaries.xml
  organs_constraints:
    leaf: input/constraints_tomato_day.txt
    stem: input/constraints_tomato_day.txt
    root: input/constraints_tomato_day.txt

biomass_rate:
  leaf: 0.21
  stem: 0.26
  root: 0.17

dry_weight_ratios:
  leaf/root: 3.37
  stem/root: 1.52

cobra_config:
  solver: glpk
    # {"glpk", "cplex", "gurobi", "glpk_exact"}
    # The default solver for new models. The solver choices are the ones
    # provided by `optlang` and depend on solvers installed in your environment.
  bounds: (-1000.0, 1000.0)
    # The default reaction bounds for newly created reactions. The bounds
    # are in the form of lower_bound, upper_bound (default -1000.0, 1000.0).
